// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: mavstate.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>
#include <vk_sdk/Preamble.hpp>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1000002
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include "header.capnp.h"

CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

VK_SDK_API extern ::capnp::word const* const bp_a9636734dfdb576f;
VK_SDK_API extern const ::capnp::_::RawSchema s_a9636734dfdb576f;
VK_SDK_API extern ::capnp::word const* const bp_dedca9bd4a3b49fe;
VK_SDK_API extern const ::capnp::_::RawSchema s_dedca9bd4a3b49fe;
enum class FlightModePX4_dedca9bd4a3b49fe: uint16_t {
  UNKNOWN,
  READY,
  TAKEOFF,
  HOLD,
  MISSION,
  RETURN_TO_LAUNCH,
  LAND,
  OFFBOARD,
  FOLLOW_ME,
  MANUAL,
  ALTITUDE,
  POSITION,
  ACRO,
  STABILIZED,
  RATTITUDE,
};
CAPNP_DECLARE_ENUM(FlightModePX4, dedca9bd4a3b49fe);

}  // namespace schemas
}  // namespace capnp

namespace vkc {

struct MavState {
  MavState() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  typedef ::capnp::schemas::FlightModePX4_dedca9bd4a3b49fe FlightModePX4;


  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(a9636734dfdb576f, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class MavState::Reader {
public:
  typedef MavState Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasHeader() const;
  inline  ::vkc::Header::Reader getHeader() const;

  inline bool getConnected() const;

  inline bool getArmed() const;

  inline bool getGuided() const;

  inline bool getManualInput() const;

  inline  ::vkc::MavState::FlightModePX4 getModePX4() const;

  inline  ::uint8_t getSystemStatus() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class MavState::Builder {
public:
  typedef MavState Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasHeader();
  inline  ::vkc::Header::Builder getHeader();
  inline void setHeader( ::vkc::Header::Reader value);
  inline  ::vkc::Header::Builder initHeader();
  inline void adoptHeader(::capnp::Orphan< ::vkc::Header>&& value);
  inline ::capnp::Orphan< ::vkc::Header> disownHeader();

  inline bool getConnected();
  inline void setConnected(bool value);

  inline bool getArmed();
  inline void setArmed(bool value);

  inline bool getGuided();
  inline void setGuided(bool value);

  inline bool getManualInput();
  inline void setManualInput(bool value);

  inline  ::vkc::MavState::FlightModePX4 getModePX4();
  inline void setModePX4( ::vkc::MavState::FlightModePX4 value);

  inline  ::uint8_t getSystemStatus();
  inline void setSystemStatus( ::uint8_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class MavState::Pipeline {
public:
  typedef MavState Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::vkc::Header::Pipeline getHeader();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline bool MavState::Reader::hasHeader() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool MavState::Builder::hasHeader() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::vkc::Header::Reader MavState::Reader::getHeader() const {
  return ::capnp::_::PointerHelpers< ::vkc::Header>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::vkc::Header::Builder MavState::Builder::getHeader() {
  return ::capnp::_::PointerHelpers< ::vkc::Header>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::vkc::Header::Pipeline MavState::Pipeline::getHeader() {
  return  ::vkc::Header::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void MavState::Builder::setHeader( ::vkc::Header::Reader value) {
  ::capnp::_::PointerHelpers< ::vkc::Header>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::vkc::Header::Builder MavState::Builder::initHeader() {
  return ::capnp::_::PointerHelpers< ::vkc::Header>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void MavState::Builder::adoptHeader(
    ::capnp::Orphan< ::vkc::Header>&& value) {
  ::capnp::_::PointerHelpers< ::vkc::Header>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::vkc::Header> MavState::Builder::disownHeader() {
  return ::capnp::_::PointerHelpers< ::vkc::Header>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool MavState::Reader::getConnected() const {
  return _reader.getDataField<bool>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline bool MavState::Builder::getConnected() {
  return _builder.getDataField<bool>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void MavState::Builder::setConnected(bool value) {
  _builder.setDataField<bool>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool MavState::Reader::getArmed() const {
  return _reader.getDataField<bool>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline bool MavState::Builder::getArmed() {
  return _builder.getDataField<bool>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void MavState::Builder::setArmed(bool value) {
  _builder.setDataField<bool>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline bool MavState::Reader::getGuided() const {
  return _reader.getDataField<bool>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline bool MavState::Builder::getGuided() {
  return _builder.getDataField<bool>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void MavState::Builder::setGuided(bool value) {
  _builder.setDataField<bool>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

inline bool MavState::Reader::getManualInput() const {
  return _reader.getDataField<bool>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}

inline bool MavState::Builder::getManualInput() {
  return _builder.getDataField<bool>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}
inline void MavState::Builder::setManualInput(bool value) {
  _builder.setDataField<bool>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS, value);
}

inline  ::vkc::MavState::FlightModePX4 MavState::Reader::getModePX4() const {
  return _reader.getDataField< ::vkc::MavState::FlightModePX4>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::vkc::MavState::FlightModePX4 MavState::Builder::getModePX4() {
  return _builder.getDataField< ::vkc::MavState::FlightModePX4>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void MavState::Builder::setModePX4( ::vkc::MavState::FlightModePX4 value) {
  _builder.setDataField< ::vkc::MavState::FlightModePX4>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline  ::uint8_t MavState::Reader::getSystemStatus() const {
  return _reader.getDataField< ::uint8_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::uint8_t MavState::Builder::getSystemStatus() {
  return _builder.getDataField< ::uint8_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void MavState::Builder::setSystemStatus( ::uint8_t value) {
  _builder.setDataField< ::uint8_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

}  // namespace

CAPNP_END_HEADER

