// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: odometry3d.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>
#include <vk_sdk/Preamble.hpp>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1000002
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include "header.capnp.h"
#include "se3.capnp.h"
#include "twist3.capnp.h"
#include "vector3.capnp.h"

CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

VK_SDK_API extern ::capnp::word const* const bp_c1d34b33bee9e899;
VK_SDK_API extern const ::capnp::_::RawSchema s_c1d34b33bee9e899;
VK_SDK_API extern ::capnp::word const* const bp_873df206096d9eea;
VK_SDK_API extern const ::capnp::_::RawSchema s_873df206096d9eea;
VK_SDK_API extern ::capnp::word const* const bp_d7dc4eaff549ad01;
VK_SDK_API extern const ::capnp::_::RawSchema s_d7dc4eaff549ad01;
VK_SDK_API extern ::capnp::word const* const bp_9928f99e42745410;
VK_SDK_API extern const ::capnp::_::RawSchema s_9928f99e42745410;
VK_SDK_API extern ::capnp::word const* const bp_d6f119640d05c3bb;
VK_SDK_API extern const ::capnp::_::RawSchema s_d6f119640d05c3bb;
enum class BodyFrame_d6f119640d05c3bb: uint16_t {
  NWU,
  NED,
};
CAPNP_DECLARE_ENUM(BodyFrame, d6f119640d05c3bb);
VK_SDK_API extern ::capnp::word const* const bp_97943a9207456599;
VK_SDK_API extern const ::capnp::_::RawSchema s_97943a9207456599;
enum class ReferenceFrame_97943a9207456599: uint16_t {
  ENU,
  NWU,
  NED,
};
CAPNP_DECLARE_ENUM(ReferenceFrame, 97943a9207456599);
VK_SDK_API extern ::capnp::word const* const bp_fd28eb54a4a5db35;
VK_SDK_API extern const ::capnp::_::RawSchema s_fd28eb54a4a5db35;
enum class VelocityFrame_fd28eb54a4a5db35: uint16_t {
  NONE,
  BODY,
  REFERENCE,
};
CAPNP_DECLARE_ENUM(VelocityFrame, fd28eb54a4a5db35);

}  // namespace schemas
}  // namespace capnp

namespace vkc {

struct VioPose {
  VioPose() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(c1d34b33bee9e899, 2, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct VioLandmark {
  VioLandmark() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(873df206096d9eea, 3, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct VioState {
  VioState() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(d7dc4eaff549ad01, 0, 6)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Odometry3d {
  Odometry3d() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  typedef ::capnp::schemas::BodyFrame_d6f119640d05c3bb BodyFrame;

  typedef ::capnp::schemas::ReferenceFrame_97943a9207456599 ReferenceFrame;

  typedef ::capnp::schemas::VelocityFrame_fd28eb54a4a5db35 VelocityFrame;


  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(9928f99e42745410, 3, 5)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class VioPose::Reader {
public:
  typedef VioPose Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getStamp() const;

  inline bool hasPose() const;
  inline  ::vkc::Se3::Reader getPose() const;

  inline bool getKf() const;

  inline  ::int32_t getGroup() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class VioPose::Builder {
public:
  typedef VioPose Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getStamp();
  inline void setStamp( ::uint64_t value);

  inline bool hasPose();
  inline  ::vkc::Se3::Builder getPose();
  inline void setPose( ::vkc::Se3::Reader value);
  inline  ::vkc::Se3::Builder initPose();
  inline void adoptPose(::capnp::Orphan< ::vkc::Se3>&& value);
  inline ::capnp::Orphan< ::vkc::Se3> disownPose();

  inline bool getKf();
  inline void setKf(bool value);

  inline  ::int32_t getGroup();
  inline void setGroup( ::int32_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class VioPose::Pipeline {
public:
  typedef VioPose Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::vkc::Se3::Pipeline getPose();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class VioLandmark::Reader {
public:
  typedef VioLandmark Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getId() const;

  inline  ::uint64_t getHostedKfStamp() const;

  inline bool hasObservedStamps() const;
  inline  ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>::Reader getObservedStamps() const;

  inline float getInvDist() const;

  inline bool hasPoint3d() const;
  inline  ::vkc::Vector3f::Reader getPoint3d() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class VioLandmark::Builder {
public:
  typedef VioLandmark Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getId();
  inline void setId( ::uint64_t value);

  inline  ::uint64_t getHostedKfStamp();
  inline void setHostedKfStamp( ::uint64_t value);

  inline bool hasObservedStamps();
  inline  ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>::Builder getObservedStamps();
  inline void setObservedStamps( ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>::Reader value);
  inline void setObservedStamps(::kj::ArrayPtr<const  ::uint64_t> value);
  inline  ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>::Builder initObservedStamps(unsigned int size);
  inline void adoptObservedStamps(::capnp::Orphan< ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>> disownObservedStamps();

  inline float getInvDist();
  inline void setInvDist(float value);

  inline bool hasPoint3d();
  inline  ::vkc::Vector3f::Builder getPoint3d();
  inline void setPoint3d( ::vkc::Vector3f::Reader value);
  inline  ::vkc::Vector3f::Builder initPoint3d();
  inline void adoptPoint3d(::capnp::Orphan< ::vkc::Vector3f>&& value);
  inline ::capnp::Orphan< ::vkc::Vector3f> disownPoint3d();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class VioLandmark::Pipeline {
public:
  typedef VioLandmark Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::vkc::Vector3f::Pipeline getPoint3d();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class VioState::Reader {
public:
  typedef VioState Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasHeader() const;
  inline  ::vkc::Header::Reader getHeader() const;

  inline bool hasStates() const;
  inline  ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>::Reader getStates() const;

  inline bool hasFrames() const;
  inline  ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>::Reader getFrames() const;

  inline bool hasLandmarks() const;
  inline  ::capnp::List< ::vkc::VioLandmark,  ::capnp::Kind::STRUCT>::Reader getLandmarks() const;

  inline bool hasBiasGyro() const;
  inline  ::vkc::Vector3f::Reader getBiasGyro() const;

  inline bool hasBiasAccel() const;
  inline  ::vkc::Vector3f::Reader getBiasAccel() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class VioState::Builder {
public:
  typedef VioState Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasHeader();
  inline  ::vkc::Header::Builder getHeader();
  inline void setHeader( ::vkc::Header::Reader value);
  inline  ::vkc::Header::Builder initHeader();
  inline void adoptHeader(::capnp::Orphan< ::vkc::Header>&& value);
  inline ::capnp::Orphan< ::vkc::Header> disownHeader();

  inline bool hasStates();
  inline  ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>::Builder getStates();
  inline void setStates( ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>::Builder initStates(unsigned int size);
  inline void adoptStates(::capnp::Orphan< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>> disownStates();

  inline bool hasFrames();
  inline  ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>::Builder getFrames();
  inline void setFrames( ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>::Builder initFrames(unsigned int size);
  inline void adoptFrames(::capnp::Orphan< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>> disownFrames();

  inline bool hasLandmarks();
  inline  ::capnp::List< ::vkc::VioLandmark,  ::capnp::Kind::STRUCT>::Builder getLandmarks();
  inline void setLandmarks( ::capnp::List< ::vkc::VioLandmark,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::vkc::VioLandmark,  ::capnp::Kind::STRUCT>::Builder initLandmarks(unsigned int size);
  inline void adoptLandmarks(::capnp::Orphan< ::capnp::List< ::vkc::VioLandmark,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::vkc::VioLandmark,  ::capnp::Kind::STRUCT>> disownLandmarks();

  inline bool hasBiasGyro();
  inline  ::vkc::Vector3f::Builder getBiasGyro();
  inline void setBiasGyro( ::vkc::Vector3f::Reader value);
  inline  ::vkc::Vector3f::Builder initBiasGyro();
  inline void adoptBiasGyro(::capnp::Orphan< ::vkc::Vector3f>&& value);
  inline ::capnp::Orphan< ::vkc::Vector3f> disownBiasGyro();

  inline bool hasBiasAccel();
  inline  ::vkc::Vector3f::Builder getBiasAccel();
  inline void setBiasAccel( ::vkc::Vector3f::Reader value);
  inline  ::vkc::Vector3f::Builder initBiasAccel();
  inline void adoptBiasAccel(::capnp::Orphan< ::vkc::Vector3f>&& value);
  inline ::capnp::Orphan< ::vkc::Vector3f> disownBiasAccel();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class VioState::Pipeline {
public:
  typedef VioState Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::vkc::Header::Pipeline getHeader();
  inline  ::vkc::Vector3f::Pipeline getBiasGyro();
  inline  ::vkc::Vector3f::Pipeline getBiasAccel();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Odometry3d::Reader {
public:
  typedef Odometry3d Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasHeader() const;
  inline  ::vkc::Header::Reader getHeader() const;

  inline  ::vkc::Odometry3d::BodyFrame getBodyFrame() const;

  inline  ::vkc::Odometry3d::ReferenceFrame getReferenceFrame() const;

  inline  ::vkc::Odometry3d::VelocityFrame getVelocityFrame() const;

  inline bool hasPose() const;
  inline  ::vkc::Se3::Reader getPose() const;

  inline bool hasPoseCovariance() const;
  inline  ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>::Reader getPoseCovariance() const;

  inline bool hasTwist() const;
  inline  ::vkc::Twist3::Reader getTwist() const;

  inline bool hasTwistCovariance() const;
  inline  ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>::Reader getTwistCovariance() const;

  inline  ::uint32_t getResetCounter() const;

  inline float getMetricVisionFailureLikelihood() const;

  inline float getMetricInertialFailureLikelihood() const;

  inline float getEstimatedFailureModeDrift() const;

  inline  ::int8_t getMetricFailureVio() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Odometry3d::Builder {
public:
  typedef Odometry3d Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasHeader();
  inline  ::vkc::Header::Builder getHeader();
  inline void setHeader( ::vkc::Header::Reader value);
  inline  ::vkc::Header::Builder initHeader();
  inline void adoptHeader(::capnp::Orphan< ::vkc::Header>&& value);
  inline ::capnp::Orphan< ::vkc::Header> disownHeader();

  inline  ::vkc::Odometry3d::BodyFrame getBodyFrame();
  inline void setBodyFrame( ::vkc::Odometry3d::BodyFrame value);

  inline  ::vkc::Odometry3d::ReferenceFrame getReferenceFrame();
  inline void setReferenceFrame( ::vkc::Odometry3d::ReferenceFrame value);

  inline  ::vkc::Odometry3d::VelocityFrame getVelocityFrame();
  inline void setVelocityFrame( ::vkc::Odometry3d::VelocityFrame value);

  inline bool hasPose();
  inline  ::vkc::Se3::Builder getPose();
  inline void setPose( ::vkc::Se3::Reader value);
  inline  ::vkc::Se3::Builder initPose();
  inline void adoptPose(::capnp::Orphan< ::vkc::Se3>&& value);
  inline ::capnp::Orphan< ::vkc::Se3> disownPose();

  inline bool hasPoseCovariance();
  inline  ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>::Builder getPoseCovariance();
  inline void setPoseCovariance( ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>::Reader value);
  inline void setPoseCovariance(::kj::ArrayPtr<const float> value);
  inline  ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>::Builder initPoseCovariance(unsigned int size);
  inline void adoptPoseCovariance(::capnp::Orphan< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>>&& value);
  inline ::capnp::Orphan< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>> disownPoseCovariance();

  inline bool hasTwist();
  inline  ::vkc::Twist3::Builder getTwist();
  inline void setTwist( ::vkc::Twist3::Reader value);
  inline  ::vkc::Twist3::Builder initTwist();
  inline void adoptTwist(::capnp::Orphan< ::vkc::Twist3>&& value);
  inline ::capnp::Orphan< ::vkc::Twist3> disownTwist();

  inline bool hasTwistCovariance();
  inline  ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>::Builder getTwistCovariance();
  inline void setTwistCovariance( ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>::Reader value);
  inline void setTwistCovariance(::kj::ArrayPtr<const float> value);
  inline  ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>::Builder initTwistCovariance(unsigned int size);
  inline void adoptTwistCovariance(::capnp::Orphan< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>>&& value);
  inline ::capnp::Orphan< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>> disownTwistCovariance();

  inline  ::uint32_t getResetCounter();
  inline void setResetCounter( ::uint32_t value);

  inline float getMetricVisionFailureLikelihood();
  inline void setMetricVisionFailureLikelihood(float value);

  inline float getMetricInertialFailureLikelihood();
  inline void setMetricInertialFailureLikelihood(float value);

  inline float getEstimatedFailureModeDrift();
  inline void setEstimatedFailureModeDrift(float value);

  inline  ::int8_t getMetricFailureVio();
  inline void setMetricFailureVio( ::int8_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Odometry3d::Pipeline {
public:
  typedef Odometry3d Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::vkc::Header::Pipeline getHeader();
  inline  ::vkc::Se3::Pipeline getPose();
  inline  ::vkc::Twist3::Pipeline getTwist();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline  ::uint64_t VioPose::Reader::getStamp() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t VioPose::Builder::getStamp() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void VioPose::Builder::setStamp( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool VioPose::Reader::hasPose() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool VioPose::Builder::hasPose() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::vkc::Se3::Reader VioPose::Reader::getPose() const {
  return ::capnp::_::PointerHelpers< ::vkc::Se3>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::vkc::Se3::Builder VioPose::Builder::getPose() {
  return ::capnp::_::PointerHelpers< ::vkc::Se3>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::vkc::Se3::Pipeline VioPose::Pipeline::getPose() {
  return  ::vkc::Se3::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void VioPose::Builder::setPose( ::vkc::Se3::Reader value) {
  ::capnp::_::PointerHelpers< ::vkc::Se3>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::vkc::Se3::Builder VioPose::Builder::initPose() {
  return ::capnp::_::PointerHelpers< ::vkc::Se3>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void VioPose::Builder::adoptPose(
    ::capnp::Orphan< ::vkc::Se3>&& value) {
  ::capnp::_::PointerHelpers< ::vkc::Se3>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::vkc::Se3> VioPose::Builder::disownPose() {
  return ::capnp::_::PointerHelpers< ::vkc::Se3>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool VioPose::Reader::getKf() const {
  return _reader.getDataField<bool>(
      ::capnp::bounded<64>() * ::capnp::ELEMENTS);
}

inline bool VioPose::Builder::getKf() {
  return _builder.getDataField<bool>(
      ::capnp::bounded<64>() * ::capnp::ELEMENTS);
}
inline void VioPose::Builder::setKf(bool value) {
  _builder.setDataField<bool>(
      ::capnp::bounded<64>() * ::capnp::ELEMENTS, value);
}

inline  ::int32_t VioPose::Reader::getGroup() const {
  return _reader.getDataField< ::int32_t>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}

inline  ::int32_t VioPose::Builder::getGroup() {
  return _builder.getDataField< ::int32_t>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}
inline void VioPose::Builder::setGroup( ::int32_t value) {
  _builder.setDataField< ::int32_t>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t VioLandmark::Reader::getId() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t VioLandmark::Builder::getId() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void VioLandmark::Builder::setId( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t VioLandmark::Reader::getHostedKfStamp() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t VioLandmark::Builder::getHostedKfStamp() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void VioLandmark::Builder::setHostedKfStamp( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline bool VioLandmark::Reader::hasObservedStamps() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool VioLandmark::Builder::hasObservedStamps() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>::Reader VioLandmark::Reader::getObservedStamps() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>::Builder VioLandmark::Builder::getObservedStamps() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void VioLandmark::Builder::setObservedStamps( ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline void VioLandmark::Builder::setObservedStamps(::kj::ArrayPtr<const  ::uint64_t> value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>::Builder VioLandmark::Builder::initObservedStamps(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void VioLandmark::Builder::adoptObservedStamps(
    ::capnp::Orphan< ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>> VioLandmark::Builder::disownObservedStamps() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint64_t,  ::capnp::Kind::PRIMITIVE>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline float VioLandmark::Reader::getInvDist() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS);
}

inline float VioLandmark::Builder::getInvDist() {
  return _builder.getDataField<float>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS);
}
inline void VioLandmark::Builder::setInvDist(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS, value);
}

inline bool VioLandmark::Reader::hasPoint3d() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool VioLandmark::Builder::hasPoint3d() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::vkc::Vector3f::Reader VioLandmark::Reader::getPoint3d() const {
  return ::capnp::_::PointerHelpers< ::vkc::Vector3f>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::vkc::Vector3f::Builder VioLandmark::Builder::getPoint3d() {
  return ::capnp::_::PointerHelpers< ::vkc::Vector3f>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::vkc::Vector3f::Pipeline VioLandmark::Pipeline::getPoint3d() {
  return  ::vkc::Vector3f::Pipeline(_typeless.getPointerField(1));
}
#endif  // !CAPNP_LITE
inline void VioLandmark::Builder::setPoint3d( ::vkc::Vector3f::Reader value) {
  ::capnp::_::PointerHelpers< ::vkc::Vector3f>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::vkc::Vector3f::Builder VioLandmark::Builder::initPoint3d() {
  return ::capnp::_::PointerHelpers< ::vkc::Vector3f>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void VioLandmark::Builder::adoptPoint3d(
    ::capnp::Orphan< ::vkc::Vector3f>&& value) {
  ::capnp::_::PointerHelpers< ::vkc::Vector3f>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::vkc::Vector3f> VioLandmark::Builder::disownPoint3d() {
  return ::capnp::_::PointerHelpers< ::vkc::Vector3f>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool VioState::Reader::hasHeader() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool VioState::Builder::hasHeader() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::vkc::Header::Reader VioState::Reader::getHeader() const {
  return ::capnp::_::PointerHelpers< ::vkc::Header>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::vkc::Header::Builder VioState::Builder::getHeader() {
  return ::capnp::_::PointerHelpers< ::vkc::Header>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::vkc::Header::Pipeline VioState::Pipeline::getHeader() {
  return  ::vkc::Header::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void VioState::Builder::setHeader( ::vkc::Header::Reader value) {
  ::capnp::_::PointerHelpers< ::vkc::Header>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::vkc::Header::Builder VioState::Builder::initHeader() {
  return ::capnp::_::PointerHelpers< ::vkc::Header>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void VioState::Builder::adoptHeader(
    ::capnp::Orphan< ::vkc::Header>&& value) {
  ::capnp::_::PointerHelpers< ::vkc::Header>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::vkc::Header> VioState::Builder::disownHeader() {
  return ::capnp::_::PointerHelpers< ::vkc::Header>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool VioState::Reader::hasStates() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool VioState::Builder::hasStates() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>::Reader VioState::Reader::getStates() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>::Builder VioState::Builder::getStates() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void VioState::Builder::setStates( ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>::Builder VioState::Builder::initStates(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void VioState::Builder::adoptStates(
    ::capnp::Orphan< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>> VioState::Builder::disownStates() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool VioState::Reader::hasFrames() const {
  return !_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline bool VioState::Builder::hasFrames() {
  return !_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>::Reader VioState::Reader::getFrames() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>::Builder VioState::Builder::getFrames() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline void VioState::Builder::setFrames( ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>::Builder VioState::Builder::initFrames(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), size);
}
inline void VioState::Builder::adoptFrames(
    ::capnp::Orphan< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>> VioState::Builder::disownFrames() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::vkc::VioPose,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}

inline bool VioState::Reader::hasLandmarks() const {
  return !_reader.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS).isNull();
}
inline bool VioState::Builder::hasLandmarks() {
  return !_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::vkc::VioLandmark,  ::capnp::Kind::STRUCT>::Reader VioState::Reader::getLandmarks() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::vkc::VioLandmark,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::vkc::VioLandmark,  ::capnp::Kind::STRUCT>::Builder VioState::Builder::getLandmarks() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::vkc::VioLandmark,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}
inline void VioState::Builder::setLandmarks( ::capnp::List< ::vkc::VioLandmark,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::vkc::VioLandmark,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::vkc::VioLandmark,  ::capnp::Kind::STRUCT>::Builder VioState::Builder::initLandmarks(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::vkc::VioLandmark,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), size);
}
inline void VioState::Builder::adoptLandmarks(
    ::capnp::Orphan< ::capnp::List< ::vkc::VioLandmark,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::vkc::VioLandmark,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::vkc::VioLandmark,  ::capnp::Kind::STRUCT>> VioState::Builder::disownLandmarks() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::vkc::VioLandmark,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}

inline bool VioState::Reader::hasBiasGyro() const {
  return !_reader.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS).isNull();
}
inline bool VioState::Builder::hasBiasGyro() {
  return !_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS).isNull();
}
inline  ::vkc::Vector3f::Reader VioState::Reader::getBiasGyro() const {
  return ::capnp::_::PointerHelpers< ::vkc::Vector3f>::get(_reader.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS));
}
inline  ::vkc::Vector3f::Builder VioState::Builder::getBiasGyro() {
  return ::capnp::_::PointerHelpers< ::vkc::Vector3f>::get(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::vkc::Vector3f::Pipeline VioState::Pipeline::getBiasGyro() {
  return  ::vkc::Vector3f::Pipeline(_typeless.getPointerField(4));
}
#endif  // !CAPNP_LITE
inline void VioState::Builder::setBiasGyro( ::vkc::Vector3f::Reader value) {
  ::capnp::_::PointerHelpers< ::vkc::Vector3f>::set(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS), value);
}
inline  ::vkc::Vector3f::Builder VioState::Builder::initBiasGyro() {
  return ::capnp::_::PointerHelpers< ::vkc::Vector3f>::init(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS));
}
inline void VioState::Builder::adoptBiasGyro(
    ::capnp::Orphan< ::vkc::Vector3f>&& value) {
  ::capnp::_::PointerHelpers< ::vkc::Vector3f>::adopt(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::vkc::Vector3f> VioState::Builder::disownBiasGyro() {
  return ::capnp::_::PointerHelpers< ::vkc::Vector3f>::disown(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS));
}

inline bool VioState::Reader::hasBiasAccel() const {
  return !_reader.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS).isNull();
}
inline bool VioState::Builder::hasBiasAccel() {
  return !_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS).isNull();
}
inline  ::vkc::Vector3f::Reader VioState::Reader::getBiasAccel() const {
  return ::capnp::_::PointerHelpers< ::vkc::Vector3f>::get(_reader.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS));
}
inline  ::vkc::Vector3f::Builder VioState::Builder::getBiasAccel() {
  return ::capnp::_::PointerHelpers< ::vkc::Vector3f>::get(_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::vkc::Vector3f::Pipeline VioState::Pipeline::getBiasAccel() {
  return  ::vkc::Vector3f::Pipeline(_typeless.getPointerField(5));
}
#endif  // !CAPNP_LITE
inline void VioState::Builder::setBiasAccel( ::vkc::Vector3f::Reader value) {
  ::capnp::_::PointerHelpers< ::vkc::Vector3f>::set(_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS), value);
}
inline  ::vkc::Vector3f::Builder VioState::Builder::initBiasAccel() {
  return ::capnp::_::PointerHelpers< ::vkc::Vector3f>::init(_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS));
}
inline void VioState::Builder::adoptBiasAccel(
    ::capnp::Orphan< ::vkc::Vector3f>&& value) {
  ::capnp::_::PointerHelpers< ::vkc::Vector3f>::adopt(_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::vkc::Vector3f> VioState::Builder::disownBiasAccel() {
  return ::capnp::_::PointerHelpers< ::vkc::Vector3f>::disown(_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS));
}

inline bool Odometry3d::Reader::hasHeader() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Odometry3d::Builder::hasHeader() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::vkc::Header::Reader Odometry3d::Reader::getHeader() const {
  return ::capnp::_::PointerHelpers< ::vkc::Header>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::vkc::Header::Builder Odometry3d::Builder::getHeader() {
  return ::capnp::_::PointerHelpers< ::vkc::Header>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::vkc::Header::Pipeline Odometry3d::Pipeline::getHeader() {
  return  ::vkc::Header::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void Odometry3d::Builder::setHeader( ::vkc::Header::Reader value) {
  ::capnp::_::PointerHelpers< ::vkc::Header>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::vkc::Header::Builder Odometry3d::Builder::initHeader() {
  return ::capnp::_::PointerHelpers< ::vkc::Header>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Odometry3d::Builder::adoptHeader(
    ::capnp::Orphan< ::vkc::Header>&& value) {
  ::capnp::_::PointerHelpers< ::vkc::Header>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::vkc::Header> Odometry3d::Builder::disownHeader() {
  return ::capnp::_::PointerHelpers< ::vkc::Header>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline  ::vkc::Odometry3d::BodyFrame Odometry3d::Reader::getBodyFrame() const {
  return _reader.getDataField< ::vkc::Odometry3d::BodyFrame>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::vkc::Odometry3d::BodyFrame Odometry3d::Builder::getBodyFrame() {
  return _builder.getDataField< ::vkc::Odometry3d::BodyFrame>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Odometry3d::Builder::setBodyFrame( ::vkc::Odometry3d::BodyFrame value) {
  _builder.setDataField< ::vkc::Odometry3d::BodyFrame>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::vkc::Odometry3d::ReferenceFrame Odometry3d::Reader::getReferenceFrame() const {
  return _reader.getDataField< ::vkc::Odometry3d::ReferenceFrame>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::vkc::Odometry3d::ReferenceFrame Odometry3d::Builder::getReferenceFrame() {
  return _builder.getDataField< ::vkc::Odometry3d::ReferenceFrame>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void Odometry3d::Builder::setReferenceFrame( ::vkc::Odometry3d::ReferenceFrame value) {
  _builder.setDataField< ::vkc::Odometry3d::ReferenceFrame>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline  ::vkc::Odometry3d::VelocityFrame Odometry3d::Reader::getVelocityFrame() const {
  return _reader.getDataField< ::vkc::Odometry3d::VelocityFrame>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::vkc::Odometry3d::VelocityFrame Odometry3d::Builder::getVelocityFrame() {
  return _builder.getDataField< ::vkc::Odometry3d::VelocityFrame>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void Odometry3d::Builder::setVelocityFrame( ::vkc::Odometry3d::VelocityFrame value) {
  _builder.setDataField< ::vkc::Odometry3d::VelocityFrame>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

inline bool Odometry3d::Reader::hasPose() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool Odometry3d::Builder::hasPose() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::vkc::Se3::Reader Odometry3d::Reader::getPose() const {
  return ::capnp::_::PointerHelpers< ::vkc::Se3>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::vkc::Se3::Builder Odometry3d::Builder::getPose() {
  return ::capnp::_::PointerHelpers< ::vkc::Se3>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::vkc::Se3::Pipeline Odometry3d::Pipeline::getPose() {
  return  ::vkc::Se3::Pipeline(_typeless.getPointerField(1));
}
#endif  // !CAPNP_LITE
inline void Odometry3d::Builder::setPose( ::vkc::Se3::Reader value) {
  ::capnp::_::PointerHelpers< ::vkc::Se3>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::vkc::Se3::Builder Odometry3d::Builder::initPose() {
  return ::capnp::_::PointerHelpers< ::vkc::Se3>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void Odometry3d::Builder::adoptPose(
    ::capnp::Orphan< ::vkc::Se3>&& value) {
  ::capnp::_::PointerHelpers< ::vkc::Se3>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::vkc::Se3> Odometry3d::Builder::disownPose() {
  return ::capnp::_::PointerHelpers< ::vkc::Se3>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool Odometry3d::Reader::hasPoseCovariance() const {
  return !_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline bool Odometry3d::Builder::hasPoseCovariance() {
  return !_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>::Reader Odometry3d::Reader::getPoseCovariance() const {
  return ::capnp::_::PointerHelpers< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>>::get(_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline  ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>::Builder Odometry3d::Builder::getPoseCovariance() {
  return ::capnp::_::PointerHelpers< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>>::get(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline void Odometry3d::Builder::setPoseCovariance( ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
inline void Odometry3d::Builder::setPoseCovariance(::kj::ArrayPtr<const float> value) {
  ::capnp::_::PointerHelpers< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>::Builder Odometry3d::Builder::initPoseCovariance(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>>::init(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), size);
}
inline void Odometry3d::Builder::adoptPoseCovariance(
    ::capnp::Orphan< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>>::adopt(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>> Odometry3d::Builder::disownPoseCovariance() {
  return ::capnp::_::PointerHelpers< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>>::disown(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}

inline bool Odometry3d::Reader::hasTwist() const {
  return !_reader.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS).isNull();
}
inline bool Odometry3d::Builder::hasTwist() {
  return !_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS).isNull();
}
inline  ::vkc::Twist3::Reader Odometry3d::Reader::getTwist() const {
  return ::capnp::_::PointerHelpers< ::vkc::Twist3>::get(_reader.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}
inline  ::vkc::Twist3::Builder Odometry3d::Builder::getTwist() {
  return ::capnp::_::PointerHelpers< ::vkc::Twist3>::get(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::vkc::Twist3::Pipeline Odometry3d::Pipeline::getTwist() {
  return  ::vkc::Twist3::Pipeline(_typeless.getPointerField(3));
}
#endif  // !CAPNP_LITE
inline void Odometry3d::Builder::setTwist( ::vkc::Twist3::Reader value) {
  ::capnp::_::PointerHelpers< ::vkc::Twist3>::set(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), value);
}
inline  ::vkc::Twist3::Builder Odometry3d::Builder::initTwist() {
  return ::capnp::_::PointerHelpers< ::vkc::Twist3>::init(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}
inline void Odometry3d::Builder::adoptTwist(
    ::capnp::Orphan< ::vkc::Twist3>&& value) {
  ::capnp::_::PointerHelpers< ::vkc::Twist3>::adopt(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::vkc::Twist3> Odometry3d::Builder::disownTwist() {
  return ::capnp::_::PointerHelpers< ::vkc::Twist3>::disown(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}

inline bool Odometry3d::Reader::hasTwistCovariance() const {
  return !_reader.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS).isNull();
}
inline bool Odometry3d::Builder::hasTwistCovariance() {
  return !_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>::Reader Odometry3d::Reader::getTwistCovariance() const {
  return ::capnp::_::PointerHelpers< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>>::get(_reader.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS));
}
inline  ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>::Builder Odometry3d::Builder::getTwistCovariance() {
  return ::capnp::_::PointerHelpers< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>>::get(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS));
}
inline void Odometry3d::Builder::setTwistCovariance( ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS), value);
}
inline void Odometry3d::Builder::setTwistCovariance(::kj::ArrayPtr<const float> value) {
  ::capnp::_::PointerHelpers< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>::Builder Odometry3d::Builder::initTwistCovariance(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>>::init(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS), size);
}
inline void Odometry3d::Builder::adoptTwistCovariance(
    ::capnp::Orphan< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>>::adopt(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>> Odometry3d::Builder::disownTwistCovariance() {
  return ::capnp::_::PointerHelpers< ::capnp::List<float,  ::capnp::Kind::PRIMITIVE>>::disown(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS));
}

inline  ::uint32_t Odometry3d::Reader::getResetCounter() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t Odometry3d::Builder::getResetCounter() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void Odometry3d::Builder::setResetCounter( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

inline float Odometry3d::Reader::getMetricVisionFailureLikelihood() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}

inline float Odometry3d::Builder::getMetricVisionFailureLikelihood() {
  return _builder.getDataField<float>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}
inline void Odometry3d::Builder::setMetricVisionFailureLikelihood(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS, value);
}

inline float Odometry3d::Reader::getMetricInertialFailureLikelihood() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS);
}

inline float Odometry3d::Builder::getMetricInertialFailureLikelihood() {
  return _builder.getDataField<float>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS);
}
inline void Odometry3d::Builder::setMetricInertialFailureLikelihood(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS, value);
}

inline float Odometry3d::Reader::getEstimatedFailureModeDrift() const {
  return _reader.getDataField<float>(
      ::capnp::bounded<5>() * ::capnp::ELEMENTS);
}

inline float Odometry3d::Builder::getEstimatedFailureModeDrift() {
  return _builder.getDataField<float>(
      ::capnp::bounded<5>() * ::capnp::ELEMENTS);
}
inline void Odometry3d::Builder::setEstimatedFailureModeDrift(float value) {
  _builder.setDataField<float>(
      ::capnp::bounded<5>() * ::capnp::ELEMENTS, value);
}

inline  ::int8_t Odometry3d::Reader::getMetricFailureVio() const {
  return _reader.getDataField< ::int8_t>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS);
}

inline  ::int8_t Odometry3d::Builder::getMetricFailureVio() {
  return _builder.getDataField< ::int8_t>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS);
}
inline void Odometry3d::Builder::setMetricFailureVio( ::int8_t value) {
  _builder.setDataField< ::int8_t>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS, value);
}

}  // namespace

CAPNP_END_HEADER

